trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseNode@2
  inputs:
    version: '14.x'
- script: |
    npm install
    npm test
    npm run lint
    npm audit
  displayName: 'Run npm commands'
