name: CI Pipeline

on:
  push:
    branches: [ main]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22.1.0'
    - name: Install dependencies
      run: npm install
    - name: Run tests
      run: npm test
    - name: Run static code analysis
      run: npm run lint
    - name: Security scan
      run: npm audit
